# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: distributed_system.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'distributed_system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64istributed_system.proto\",\n\x04Node\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\"\x84\x01\n\x0f\x46ileSystemState\x12\x33\n\nnode_files\x18\x01 \x03(\x0b\x32\x1f.FileSystemState.NodeFilesEntry\x1a<\n\x0eNodeFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.NodeFiles:\x02\x38\x01\"1\n\x0bReadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\"0\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t\"C\n\x0cWriteRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\x05\"1\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t\"\x1a\n\tNodeFiles\x12\r\n\x05\x66iles\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\\\n\tSuperNode\x12\x1f\n\x0eGiveRandomNode\x12\x06.Empty\x1a\x05.Node\x12.\n\x12GetFileSystemState\x12\x06.Empty\x1a\x10.FileSystemState2\x8b\x01\n\x08\x44\x61taNode\x12*\n\x0bRequestRead\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12-\n\x0cRequestWrite\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12$\n\x0eGetFilesOnNode\x12\x06.Empty\x1a\n.NodeFilesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributed_system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILESYSTEMSTATE_NODEFILESENTRY']._loaded_options = None
  _globals['_FILESYSTEMSTATE_NODEFILESENTRY']._serialized_options = b'8\001'
  _globals['_NODE']._serialized_start=28
  _globals['_NODE']._serialized_end=72
  _globals['_FILESYSTEMSTATE']._serialized_start=75
  _globals['_FILESYSTEMSTATE']._serialized_end=207
  _globals['_FILESYSTEMSTATE_NODEFILESENTRY']._serialized_start=147
  _globals['_FILESYSTEMSTATE_NODEFILESENTRY']._serialized_end=207
  _globals['_READREQUEST']._serialized_start=209
  _globals['_READREQUEST']._serialized_end=258
  _globals['_READRESPONSE']._serialized_start=260
  _globals['_READRESPONSE']._serialized_end=308
  _globals['_WRITEREQUEST']._serialized_start=310
  _globals['_WRITEREQUEST']._serialized_end=377
  _globals['_WRITERESPONSE']._serialized_start=379
  _globals['_WRITERESPONSE']._serialized_end=428
  _globals['_NODEFILES']._serialized_start=430
  _globals['_NODEFILES']._serialized_end=456
  _globals['_EMPTY']._serialized_start=458
  _globals['_EMPTY']._serialized_end=465
  _globals['_SUPERNODE']._serialized_start=467
  _globals['_SUPERNODE']._serialized_end=559
  _globals['_DATANODE']._serialized_start=562
  _globals['_DATANODE']._serialized_end=701
# @@protoc_insertion_point(module_scope)
